USE flight_ai_game;
/* Insert 6 easy, 7 medium, 7 hard. Update file_path to match real files in backend/static/images/... */
INSERT INTO images (id, level, file_path, original_prompt, active) VALUES
(UUID(),'easy','images/easy/e1.png','A royal enfield black motorcycle parked under a streetlamp in a quiet alley',1),
(UUID(),'easy','images/easy/e2.png','A vintage red sports car parked in front of coffee shop',1),
(UUID(),'easy','images/easy/e3.png','A fluffy cat wearing a tiny crown, sitting on a velvet throne',1),
(UUID(),'easy','images/easy/e4.png','A golden retriever puppy playing with a red ball in a grassy field',1),
(UUID(),'easy','images/easy/e5.png','A cartoon of an old couple in front of Padmanabhaswamy Temple',1),
(UUID(),'easy','images/easy/e6.png','A steaming cup of coffee on a wooden desk next to a laptop',1),
(UUID(),'easy','images/easy/e7.png','A solitary lighthouse on a rocky shore during a storm',1),
(UUID(),'easy','images/easy/e8.png','A girl in a yellow raincoat holding a red umbrella, standing in the middle of road',1),
(UUID(),'easy','images/easy/e9.png','A child building a sandcastle on a sunny beach',1),
(UUID(),'easy','images/easy/e10.png','A giant, ancient tree with a glowing door carved into its trunk',1),

(UUID(),'medium','images/medium/med1.png','A man reading a newspaper on a park bench, pigeons nearby, autumn leaves.',1),
(UUID(),'medium','images/medium/med2.png','A kitchen with white cabinets, fresh bread on counter, yellow flowers in window',1),
(UUID(),'medium','images/medium/med3.png','A girl with braids feeding ducks at a pond, wooden bridge behind',1),
(UUID(),'medium','images/medium/med4.png','A red mailbox beside a gravel path, white house, roses in garden',1),
(UUID(),'medium','images/medium/med5.png','An old man painting at an easel outdoors, easel facing mountains, paint tubes scattered',1),
(UUID(),'medium','images/medium/med6.png','A teacher writing on blackboard, students raising hands, books stacked on desk, clock showing noon',1),
(UUID(),'medium','images/medium/med7.png','A fisherman casting line from wooden dock, tackle box open, seagulls circling overhead',1),
(UUID(),'medium','images/medium/med8.png','A gardener watering tomato plants, wheelbarrow with tools, bees buzzing around lavender bushes',1),
(UUID(),'medium','images/medium/med9.png','A mechanic under car hood, tools on ground, oil stains, radio playing nearby',1),
(UUID(),'medium','images/medium/med10.png','A picnic blanket with sandwiches, thermos, ants marching, basket tipped over, park trees',1),
(UUID(),'medium','images/medium/med11.png','A scientist looking through microscope, test tubes bubbling, lab coat stained, notes scattered',1),
(UUID(),'medium','images/medium/med12.png','A lifeguard in red chair, whistle around neck, umbrella providing shade, beach ball on sand',1),
(UUID(),'medium','images/medium/med13.png','A janitor mopping hallway, bucket with wheels, wet floor sign, keys jingling',1),
(UUID(),'medium','images/medium/med14.png','A cashier scanning items, receipt printing, shopping bags ready, customer counting coins',1),
(UUID(),'medium','images/medium/med15.png','A pilot checking instruments, headset on, clouds visible through window, coffee cup steaming',1),
(UUID(),'medium','images/medium/med16.png','A nurse taking blood pressure, stethoscope draped, chart on clipboard, patient smiling',1),
(UUID(),'medium','images/medium/med17.png','A taxi driver checking mirror, meter running, air freshener hanging, radio crackling',1),
(UUID(),'medium','images/medium/med18.png','A dentist examining teeth, light overhead, instruments on tray, patient wearing bib',1),
(UUID(),'medium','images/medium/med19.png','A painter on scaffold, brush dripping, paint cans below, ladder secured, birds perching',1),
(UUID(),'medium','images/medium/med20.png','A waiter serving soup, steam rising, bread basket on table, wine glasses filled',1),

(UUID(),'hard','images/hard/hard1.png','A chef in white hat chopping vegetables, copper pots hanging, steam rising, herb garden visible through window',1),
(UUID(),'hard','images/hard/hard2.png','Two boys flying kites on beach, seagulls overhead, sandcastle nearby, lighthouse in distance, clouds gathering',1),
(UUID(),'hard','images/hard/hard3.png','A librarian organizing books on ladder, cat sleeping below, sunlight through stained glass, teacup on desk',1),
(UUID(),'hard','images/hard/hard4.png','A farmer feeding chickens in yard, red barn background, hay bales, weathervane spinning, dog watching',1),
(UUID(),'hard','images/hard/hard5.png','A street musician with guitar, hat for coins, pigeons pecking crumbs, café umbrellas, people walking',1),
(UUID(),'hard','images/hard/hard6.png','A violinist performing in park, music sheets fluttering, coins in case, joggers passing, fountain splashing, pigeons pecking',1),
(UUID(),'hard','images/hard/hard7.png','A photographer crouching in meadow, butterfly on lens cap, camera bag open, wildflowers swaying, clouds reflected',1),
(UUID(),'hard','images/hard/hard8.png','A postman delivering mail, dog barking behind gate, letters scattered, bicycle leaning, garden gnome watching, doorbell glowing',1),
(UUID(),'hard','images/hard/hard9.png','A florist arranging roses, scissors on counter, petals fallen, customer browsing, watering can dripping, price tags visible',1),
(UUID(),'hard','images/hard/hard10.png','A construction worker hammering roof, ladder against wall, tools in belt, hard hat bright, blueprints weighted down',1),
(UUID(),'hard','images/hard/hard11.png','A zookeeper feeding penguins, fish bucket half empty, visitors watching behind glass, ice melting, name tag visible',1),
(UUID(),'hard','images/hard/hard12.png','A watchmaker repairing timepiece by seeing through magnifying glass, tiny gears scattered, oil droplets gleaming, clock ticking',1),
(UUID(),'hard','images/hard/hard13.png','A firefighter climbing ladder, hose unrolled, smoke billowing, helmet reflecting flames, radio crackling, crowds gathering below',1),
(UUID(),'hard','images/hard/hard14.png','A jeweler examining diamond, loupe in eye, velvet cloth spread with diamonds, scales gleaming, certificates stacked, safe door ajar',1),
(UUID(),'hard','images/hard/hard15.png','A archaeologist brushing artifact, dirt flying, measuring tape extended, notebook getting dusty, sun hat tilted, tools organized',1),
(UUID(),'hard','images/hard/hard16.png','A meteorologist pointing at map, storm clouds swirling, radar beeping, coffee mug steaming, papers rustling, forecast updating',1),
(UUID(),'hard','images/hard/hard17.png','A locksmith cutting keys, metal shavings falling, code book open, customer keys dangling, machine humming, receipt printing',1),
(UUID(),'hard','images/hard/hard18.png','A optometrist adjusting frames, eye chart reflecting, lens case open, prescription pad ready, patient squinting, light dimming',1),
(UUID(),'hard','images/hard/hard19.png','A beekeeper inspecting hive, smoke gun ready, protective suit zipped, honey dripping, frames lifted, bees buzzing frantically',1),
(UUID(),'hard','images/hard/hard20.png','A cobbler hammering sole, leather scraps curled, awl gleaming, thread spools organized, customer shoe waiting, lamp casting shadows',1);
